### ISSUE TITLE
submit the FIDASIM job 

### ISSUE THREAD

**Issue by gzhao2014** [D3DEnergetic/nstx-fidasim#3] opened 2016-04-27 18:37 UTC
@lstagner 
when I submit the job : qsub rjob_SPIRAL_1C
It seems there is a problem when calculate the weight function. Detailed information can be found in the file: 
/p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/rjob_SPIRAL_1C.o719909

Error message:
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libpthread.so.0    00002ACEB41E3B6D  Unknown               Unknown  Unknown
libiomp5.so        00002ACEB40AF4FE  Unknown               Unknown  Unknown
forrtl: severe (174): SIGSEGV, segmentation fault occurred
/u/ghao: Permission denied.

**Comment by lstagner** [comment] 2016-04-27 19:13
OK I know what the problem is. For now just turn off the weight function calculation.

**Comment by lstagner** [comment] 2016-04-27 21:43
OK its fixed now. I updated /p/fida/FIDASIM with the corrected version so you shouldn't have to do anything

**Closed as completed by lstagner** 2016-04-27 21:43 UTC

**Comment by gzhao2014** [comment] 2016-04-28 00:28
@lstagner 
Great. Thanks. Yes. It can work. However, it seems a little issue about display fast ion density (actually, I used the default particle # of fast ion, 10^19)

 /p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/rjob_SPIRAL_1C.o719942

> > > Mean Fast-ion Density:    0.00000E+00

**Comment by lstagner** [comment] 2016-04-28 00:47
That is expected since FIDASIM doesn't know the fast ion density when using a particle distribution so its set to zero
